version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint run
  format:
    cmds:
      - go fmt ./...
  vet:
    cmds:
      - go vet ./...
  test:
    cmds:
      - go test ./...
  check-updates:
    cmds:
      - go list -u -m all
  update:
    cmds:
      - go get -u ./...
